# Basic Configuration
baseURL = "/"
title = "CFY"
theme = "hugo-saasify-theme"

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Language Configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.cs]
    contentDir = 'content/cs'
    disabled = false
    languageCode = 'cs-CZ'
    languageDirection = 'ltr'
    languageName = 'Česky'
    title = 'Cloud4You'
    weight = 1
    [languages.cs.params]
      subtitle = 'Reference, návody a vysvětlení'
      menu = { solutions = "Řešení", pricing = "Ceník", blog = "Blog" }
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Cloud4You'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
      menu = { solutions = "Solutions", pricing = "Pricing", blog = "Blog" }

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true       # Allow HTML in markdown
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters
[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/logo.svg"      # Path to your logo
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production

  # Header Configuration
  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Header Logo
    [params.header.logo]
      src = "/images/logo.svg"
    
    # Header Buttons (optional)
    [params.header.buttons]
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "/signin"
      [params.header.buttons.getStarted]
        text = "Get Started"
        url = "/get-started"

  # Global CTA Configuration (optional)
  [params.cta]
    enable = true
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"

  # Social Media Links (optional)
  [params.social]
    linkedin = "https://www.linkedin.com/company/cfycz/?viewAsMember=true"
    #twitter = "https://twitter.com/yourusername"
    github = "https://github.com/cloud-for-you"

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Solutions"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Design IT Infrastructure", url = "/solutions/design-it-infrastructure/" },
        { name = "Penetration testing", url = "/solutions/penetration-testing/" },
        { name = "Performance", url = "/solutions/performance/" }
      ]
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3