# Basic Configuration
#baseURL = "http://cloud-for-you.github.io/webpages/"
baseURL = "http://www.cfy.cz/"
canonifyURLs = true
title = "CFY"
theme = "hugo-saasify-theme"

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Language Configuration
defaultContentLanguage = 'cs'
defaultContentLanguageInSubdir = true
[languages]
  [languages.cs]
    contentDir = 'content/cs'
    disabled = false
    languageCode = 'cs-CZ'
    languageDirection = 'ltr'
    languageName = 'Česky'
    title = 'Cloud4You'
    weight = 1
    [languages.cs.params]
      subtitle = 'Reference, návody a vysvětlení'
#  [languages.en]
#    contentDir = 'content/en'
#    disabled = false
#    languageCode = 'en-US'
#    languageDirection = 'ltr'
#    languageName = 'English'
#    title = 'Cloud4You'
#    weight = 2
#    [languages.en.params]
#      subtitle = 'Reference, Tutorials, and Explanations'

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true       # Allow HTML in markdown
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters
[params]
  description = "Cloud for You"
  author = "Petr Hatoň"
  logo = "/images/cfy_logo_b.svg"      # Path to your logo
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production

  # Header Configuration
  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Header Logo
    [params.header.logo]
      src = "/images/cfy_logo_b.svg"
    
    # Header Buttons (optional)
    [params.header.buttons]
      [params.header.buttons.signIn]
        text = "sign_in"
        url = "/signin"
      [params.header.buttons.getStarted]
        text = "get_started"
        url = "/get-started"

  # Global CTA Configuration (optional)
  [params.cta]
    enable = false
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"

  # Social Media Links (optional)
  [params.social]
    linkedin = "https://www.linkedin.com/company/cfycz/?viewAsMember=true"
    #twitter = "https://twitter.com/yourusername"
    github = "https://github.com/cloud-for-you"

# Navigation Menu
[menu]
  [[menu.main]]
    name = "solutions"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "design_it_infrastructure", url = "/solutions/design-it-infrastructure/" },
        { name = "penetration_testing", url = "/solutions/penetration-testing/" },
        { name = "technical_consultant", url = "/solutions/technical-consultant/" }
      ]
  [[menu.main]]
    name = "pricing"
    url = "/pricing"
    weight = 2
#  [[menu.main]]
#    name = "blog"
#    url = "/blog"
#    weight = 3